export const branding = {
  name: "Beachamp Academy",
  shortName: "BT",
  sport: "Volleyball",
  tagline: "Elevate Your Volleyball Game",
  description:
    "Professional volleyball coaching for all levels. Join our academy groups, improve your skills, and track your progress.",
  meta: {
    title: "Beachamp Academy — Volleyball academy Platform",
    description: "Volleyball academy management — player portals, coach tools, and admin dashboards all in one place.",
  },
  colors: {
    primary: {
      50: "#ECFEFF",
      100: "#CFFAFE",
      200: "#A5F3FC",
      300: "#67E8F9",
      400: "#22D3EE",
      500: "#06B6D4",
      600: "#0891B2",
      700: "#0E7490",
      800: "#155E75",
      900: "#164E63",
      DEFAULT: "#0891B2",
    },
    accent: {
      50: "#FBF7EC",
      100: "#F5EBD0",
      200: "#EBD7A1",
      300: "#E0C372",
      400: "#D4AA42",
      500: "#C49A38",
      600: "#A37F2E",
      700: "#826524",
      DEFAULT: "#D4AA42",
    },
    secondary: "#155E75",
    success: "#10B981",
    warning: "#F59E0B",
    danger: "#EF4444",
    sand: "#F0EBE3",
    sandDark: "#D4C8B8",
    sidebar: "#0C2340",
    brand: {
      player: "#0891B2",
      coach: "#7C3AED",
      admin: "#EF4444",
    },
    surface: {
      bg: "#F8FFFE",
      card: "#FFFFFF",
      border: "#B2E0E8",
    },
    text: {
      primary: "#0F172A",
      muted: "#64748B",
    },
    gradient: {
      primary: "from-[#0E7490] to-[#06B6D4]",
      dark: "from-[#0C2340] to-[#155E75]",
    },
  },
  areas: ["Maadi", "Zamalek", "New Cairo", "6th October", "Heliopolis", "Nasr City", "Mohandessin", "El Shorouk"],
  levels: [
    { value: "beginner", label: "Beginner" },
    { value: "intermediate", label: "Intermediate" },
    { value: "advanced", label: "Advanced" },
    { value: "professional", label: "Professional" },
  ],
  trainingGoals: [
    "Learn the basics",
    "Improve Fitness",
    "Participate in tournaments",
    "Competitive training",
    "Prepare for a season",
  ],
} as const;
